### ISSUE TITLE
Mobile user state

### ISSUE THREAD

**Issue by vijaystroup** [COP4331-Group20-Sum2021/Midpoint#20]
In reference to mobile;
Trying to check to see if a user is currently logged in and render the correct navigation drawer buttons was posing some difficulty.
Since @kyleolson812 set up the navigation, he might know it the best.

All the following methods are a result of using `const { user } = useAuth()`:
- I tried getting the user in the App function, however this is not in the Auth Context, so it had no clue about the function useAuth so this is a impossibility.
- I tried getting the user on the login and register components, however, checking this will just result in the client still being able to view the page, it's just that we can change the content, which is not ideal (we want to prevent the client from being able to navigate to the login/signup screens)
- I tried getting the user in the LoginStackScreen in App.jsx, however this cases many issues

We need some way to render the login/signup navigation buttons when there is no user detected, and when there is, render a logout button.

**Comment by kyleolson812** [comment]
I have searched through React Navigation docs and have came across this page:
https://reactnavigation.org/docs/auth-flow/

My question is would it be possible to:
1. Create a function that determines if a user is logged in.
2. Call the function from App.jsx.
3. Use an if statement to change the display based on if the user is logged in from the function we created.

I will add more information to this reply as I continue to resolve the problem. If this is not a possibility let me know asap @VijayStroup

**Comment by vijaystroup** [comment]
This looks very promising.
Give it a shot.

Also I was thinking, we could use an HOC for the screens the same way I did
in the web side, so if I user goes to the login screen, and they are logged
in, it will redirect to the home page. The only thing with this is
1. I’m not sure this will even work on react native
2. With a mobile app, we don’t really care about the user navigating to a
screen manually like they can in a web browser. It is much better to try to
prevent the signup and login buttons on the nav from showing when the user
is logged in, rather than being able to redirect them if they navigate to
the login or signup screen while being logged in.

**Comment by kyleolson812** [comment]
I have successfully figured out how to remove unwanted navigation based on user login @VijayStroup. I have been using state hooks to change whether I display or not. Now the only thing I need to understand is how we are grabbing the information that the user is logged in. Once I know how to create a function that can determine whether a user is logged in, I can apply it to the state hook and get it functioning correctly.

**Comment by vijaystroup** [comment]
I get the user from the userContext as just user.
Upon the state being loaded, the user variable will either be populated or not.
You can view the use case here: https://github.com/Nate8888/Midpoint/blob/main/web/src/components/nav.jsx
